const EErrors = {
  INCOMPLETE_DATA: 1,
  DUPLICATE_CODE: 2,
  INVALID_TYPES: 3,
  ID_NOT_FOUND: 4,
  INSUFFICIENT_STOCK: 5,
  COMISION_EMPTY: 6,
  COMISION_NOT_FOUND: 7,
  NOT_ALUMNO_EN_LA_COMISION: 8,
  NON_EXISTENT_PRODUCT: 9,
  DOCUMENT_ALREADY_LOADED: 10,
  NOT_ADD_ALUMNO: 11,
};
export default EErrors;
